week_6/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("login/", views.login_view, name="login")
]

week_6/week_6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include("tasks.urls"))
]

week_6/tasks/models.py
from django.db import models

# Create your models here.

week_6/tasks/views.py
from django import forms
from django.forms.widgets import TextInput
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse 
from django.contrib.auth import authenticate, login, logout


tasks = [ ]
# Create your views here.
class NewTaskForm(forms.Form):
    task = forms.CharField(label="Here")
    # tasks_2 = forms.CharField(label="content")

def index(request):
    # if "tasks" not in request.session:
    #     request.session["tasks"] = [ ]
    return render(request, "tasks/index.html", {
        "tasks": tasks
        # "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })


def login_view(request):
     if request.method == "POST":
         username = request.POST['username']
         password = request.POST['password']
         user = authenticate(request, username=username, password=  password)
         if user is not None:
             login(request, user)
             return HttpResponseRedirect(reverse("tasks:index"))
         else:
             return render(request, "tasks/add.html", {
                 "message" : "Invalid"
             })
     return render(request, "tasks/login.html")



# from django.contrib.auth import authenticate, login, logout
# from django.shortcuts import render
# from django.http import HttpResponseRedirect
# from django.urls import reverse

# # Create your views here.
# def index(request):
#     if not request.user.is_authenticated:
#         return HttpResponseRedirect(reverse("login"))
    

# def login_view(request):
#     if request.method == "POST":
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=  password)
#         if user is not None:
#             login(request, user)
#             return HttpResponseRedirect(reverse("index"))
#         else:
#             return render(request, "users/login.html", {
#                 "message" : "Invalid"
#             })
#     return render(request, "users/login.html")

# def logout_view(request):
#     return render(request, "users/logout.html")

# def register_view(request):
#     return render(request, "users/register.html")

week_6/tasks/templates/tasks/add.html
{% extends "tasks/layout.html"%}

{% block body%}
    
    <h1 style="text-align:center; font-size: 50PX; font-family: 'Courier'; color: brown;">ADD / POST YOUR BLOG</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        
        <h1 style="margin: auto; text-align: center;">
             {{ form}} 
             <input type="submit">
        
        </h1>
        

    </form>

    <h3 style="text-align: center;"><a href="{% url 'tasks:index' %}" >GO TO THE LANDING PAGE</a></h3>

    
{% endblock %}

week_6/tasks/templates/tasks/index.html
{% extends "tasks/layout.html"%}

{% block body%}
    <h1 style="color: coral;">LIST OF BLOGS</h1>
        <ul style="font-size: 50px;">
            {% for task in tasks %}
                <li >{{task}}</li>

            {% empty %}
                <li>No Post</li>
            {% endfor %}
        </ul>
    <a href="{% url 'tasks:login' %}" style="font-size: 50px; border-radius: 5px; background-color: coral; border: 1px solid rebeccapurple; font-family: Verdana, Geneva, Tahoma, sans-serif;">REGISTER AS A USER</a>
{% endblock %}

week_6/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="text-align:center; font-size: 80px; font-family: 'Courier New', Courier, monospace; color:brown;">THIS IS WEEK_6 DJANGO TASK</h1>
    

    {% block body%}

    {% endblock %}
    
</body>
</html>

week_6/tasks/templates/tasks/login.html
{% extends "tasks/layout.html"%}
{% block body %}

    {% if message %}

        <div>{{message}}  </div>

    {% endif %}

    <form action="{% url 'tasks:add' %}" method="POST">
        {%csrf_token%}
        <h1 style="text-align: center;">
            <input type="text" placeholder="Username" name="username" style="height: 40px; border-radius: 10px; border: 1px solid black;" > <br> <br>
            <input type="password" placeholder="Password" name="password" style="height: 40px; border-radius: 10px; border: 1px solid black;"> <br> <br>
            <input type="submit" value="login" style="height: 40px; border-radius: 10px; border: 1px solid black; font-size: 25px;">

        </h1>
       
    </form>
{% endblock %}